<?php

/**
 * This script will parse a CSV file generated by the TomTom Cardio Runner watch
 * and insert those values in the database as HR entries.
 */

require_once(dirname(__FILE__) . '/config.php');
require_once(dirname(__FILE__) . '/inc/cmd-functions.php');

assertRunningAsCmdScript();

if($argc < 4) {
    echo "Usage: \n";
    echo "  php hr2db.php <subjectId> /path/to/hr.csv /path/to/database.sqlite\n";
    exit(1);
}

$aSubjectId = $argv[1];
$aHRFile = $argv[2];
$aDatabaseFile = $argv[3];

if(!file_exists($aHRFile)) {
    echo "Unable to open HR CSV file: " . $aHRFile . "\n";
    exit(2);
}

if(!file_exists($aDatabaseFile)) {
    echo "Unable to access database file: " . $aDatabaseFile . "\n";
    exit(3);
}

$aExperiment = null;
$aData = array();
$aFile = fopen($aHRFile, 'r');

while (($aLine = fgetcsv($aFile)) !== FALSE) {
    $aData[] = array('time' => $aLine[0], 'hr' => $aLine[9]);
}
fclose($aFile);

// Remove CSV file header
unset($aData[0]);

$aDb = new PDO('sqlite:' . $aDatabaseFile);
$aDb->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

$aSubjectData = getSubjectData($aDb, $aSubjectId);

// Make sure the subject id is valid
if(!isset($aSubjectData['games']) || count($aSubjectData['games']) == 0) {
    echo 'Subject has no data in the database. Is "'.$aSubjectId.'" a valid subject id?' . "\n";
    exit(4);
}

// Make sure subject has no HR data
if(subjectHasHRData($aSubjectData)) {
    echo 'Subject with id '.$aSubjectId.' already has HR data.' . "\n";
    exit(5);
}

$aStmt = $aDb->prepare("SELECT * FROM logs WHERE uuid = :uuid AND data LIKE '%experiment_hr_start%'");
$aStmt->bindParam(':uuid', $aSubjectId);
$aStmt->execute();

while($aRow = $aStmt->fetch(PDO::FETCH_ASSOC)) {
    $aExperiment[] = $aRow;
}

if($aExperiment == null) {
    echo "Subject with id ".$aSubjectId." has no experiment_hr_start.\n";
    exit(6);
}

if(count($aExperiment) > 1) {
    echo "Subject with id ".$aSubjectId." has multiple experiment_hr_start.\n";
    exit(7);
}

$aTimestampStart = $aExperiment[0]['timestamp'] + 0;

// Start a transaction to ensure the following inserts are executed
// without lots of IO waiting.
$aDb->beginTransaction();

foreach($aData as $aRow) {
    $aHR            = $aRow['hr'] == '' ? 0 : $aRow['hr'];
    $aRelativeTime  = $aRow['time'] + 0;
    $aTime          = $aTimestampStart + $aRelativeTime;
    $aJsonData      = '[{"t":' . $aTime .'000,"d":"{\"hr\":' . $aHR . '}"}]';

    $aDb->query("INSERT INTO logs (fk_game, timestamp, uuid, data) VALUES (-1, ".$aTime.", '".$aSubjectId."', '".$aJsonData."')");
}

// Finish the transaction to persit data.
$aDb->commit();

echo "All done!\n";

?>
